version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ego-frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ego-backend
    ports:
      - "4001:4001"
