name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.KEY }}
          source: ./
          target: ~/home/ubuntu/backend/

      - name: Connect to EC2 instance and deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/home/ubuntu/backend
            sudo npm install
            rm .env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "PRODUCTION_URL=${{ secrets.PRODUCTION_URL }}" >> .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
            echo "EXPIRES_IN =${{ secrets.EXPIRES_IN  }}" >> .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
            echo "PRODUCTION_URL=${{ secrets.PRODUCTION_URL }}" >> .env
            pm2 stop backend
            pm2 delete backend
            pm2 start npm --name "backend" -- start
